name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flask pytest

    - name: Run tests
      run: pytest test_app.py

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: 352a0968-81ee-450f-9fc1-0f90267e9893
        tenant-id: 4f63173d-82be-4c8f-972c-c90cc761d3b9
        subscription-id: 928560d6-60fe-49a8-aa82-9ef8898cf9bc

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: my-flask-devops-app
        package: my-devops-app